name: x86-64 Pull and Save Docker Image
on:
  workflow_dispatch:
    inputs:
      environment:
        description: '请填写docker镜像名称 多个用英文逗号分开'
        required: true
        default: 'alpine:latest'  # 设置默认的 Docker 镜像列表

